---
title: "gapminder"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
gapminder <- read_csv("https://raw.githubusercontent.com/jules32/2017-11-30-MBARI/gh-pages/data/gapminder.csv")
```

```{r}
head(gapminder, 3)
tail(gapminder, 10)
```

```{r}
str(gapminder)
```

```{r}
dim(gapminder)
ncol(gapminder)
nrow(gapminder)
```

```{r}
unique(gapminder$country)
```

```{r}
summary(gapminder)
```

```{r}
#install.packages("skimr")
library("skimr")
skim(gapminder)
```
#Manipulate Gapminder dataset
```{r}
filter(gapminder,  lifeExp < 30)
filter(gapminder, country == "Afghanistan", year == max(year))
```

```{r}
select(gapminder, country, year, pop)
filter(gapminder, year == 2007)
```

```{r}
select(gapminder, -continent) %>%
  filter(year == 2007)
```

```{r}
gapminder %>%
  mutate(gdp = gdpPercap * pop) %>%
  arrange(desc(gdp))
```

```{r}
gapminder %>%
  group_by(country) %>%
  mutate(gdp = gdpPercap * pop, max_gdp = max(gdp)) %>%
  ungroup()
```

```{r}
gapminder %>%
  group_by(country) %>%
  mutate(gdp = gdpPercap * pop) %>%
  summarize(gdp_max = max(gdp))
  
  
  
```

#Load CO2 data
```{r}
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")
```
# join co2 and gapminder datasets
```{r}
head(co2)
```
```{r}
gap2007 <- gapminder %>%
  filter(year == 2007)
```

```{r}
right_join(gap2007, co2, by = "country")
```
##Tidyr

```{r}
AirPassengers
```
```{r}
gather(AirPassengers, "year", "month")
#doesn't work due to a weird header format
```

```{r}
gapwide <- read.csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder_wide.csv")
```

```{r}
gap_better <- gapwide %>%
  gather(observation, observ_value, -continent, -country) %>%
  separate(observation, into = c("obs_type", "year"), sep = "_", convert = TRUE)
```

```{r}
unique(gap_better$obs_type)
```

```{r}
gap_better %>%
  spread(obs_type, observ_value)
```

